name: Valgrind Analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Dynamic Analysis
      run: gcc calendar_main.c src/calendar.c -o valgrind.out
    - name: valgrind 
      run: valgrind ./valgrind.out
