name: Windows C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: direction
    - run: cd 3_Implementation
    - name: build
      run: gcc calendar_main.c src/calendar.c -o calendar.exe
    - name: Run
      run: .\calendar.exe
    
